use_frameworks!
inhibit_all_warnings!

platform :ios, '12.0'

target 'TYUtils_Example' do
  pod 'TYUtils', :path => '../', :inhibit_warnings => false
  pod 'SwiftLint' # (0.42.0)

  target 'TYUtils_Tests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    # Let the project define the deployment target of pods
    # https://www.jessesquires.com/blog/2020/07/20/xcode-12-drops-support-for-ios-8-fix-for-cocoapods/
    puts "Cleaning IPHONEOS_DEPLOYMENT_TARGET from pods build settings"
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
      end
    end
  end
end
