# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode12.2 
language: swift
xcode_workspace: Example/TYUtils.xcworkspace
xcode_scheme: TYUtils-Example
xcode_destination: platform=iOS Simulator,OS=14.2,name=iPhone 12 Pro Max
xcode_sdk: iphonesimulator14.2
podfile: Example/Podfile

branches:
  only:
  - master
  - /\d+\.\d+(\.\d+)?(-\S*)?$/

before_install:
  - gem install cocoapods

install:
  - pod install --project-directory=Example

script:
  - set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace "$TRAVIS_XCODE_WORKSPACE" -scheme "$TRAVIS_XCODE_SCHEME" -sdk "$TRAVIS_XCODE_SDK" -destination "$TRAVIS_XCODE_DESTINATION" only_active_arch=no | xcpretty
  - pod lib lint
