# https://github.com/ty0x2333/cocoapods-action
on: push
jobs:
  test:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@master
    - name: Set XCode Version
      run: sudo xcode-select -s /Applications/Xcode_12.3.app
    - name: Install Dependencies
      run: |
        cd Example
        pod install --repo-update
      shell: bash
    - uses: ty0x2333/cocoapods-action@master
      with:
        workspace: Example/TYUtils.xcworkspace
        scheme: TYUtils-Example
        use_modern_build_system: true
        additional_build_params: -destination 'platform=iOS Simulator,OS=14.3,name=iPhone 12 Pro Max'
